### ISSUE TITLE
Create skills underpinning 'Accessibility' competency

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webliteracymap#16]
We decided on the [29th January community call](http://webliteracy.tumblr.com/post/109569896329/weblitmap-29jan) to separate out 'Design & Accessibility' into two discrete competencies.This has been reflected in the repo (#13). Now we need to come up with the skills for **Accessibility**.

For reference, v1.1:
* [Design & Accessibility](https://webmaker.org/en-US/resources/literacy/weblit-DesignAccessibility)

**Comment by sometimesmotion** [comment]
I think that empathy, awareness and design/planning are important for this competency:

From design:
*Improving the accessibility of a web page by modifying its color scheme and markup
*Designing the structure of a web page to improve its hierarchy/conceptual flow (changed 'reorganzing to designing to highlight proactive planning, not retroactive fixing)

Potential new skills:
*Empathizing with all users and identifying how specific user interactions are accessed by people possessing varying abilities 
*Developing an awareness of the ways in which people with disabilities access content on the Web
*Using strategies and tools to assess and improve accessibility

#1 & #5 are fairly similar and could potentially be combined - my intention was to add the assessment/evaluation of a site's accessibility

**Comment by jgmac1106** [comment]
I like trying to get at awareness and empathy, and kudos on thinking about this as something you do first rather than fix later.

- Using HTML Tags to make navigation explicit to all readers.
- Designing the structure of a web page to make hierarchy evident.
- Using text alternatives to make images accessible to all readers.

I had originally thought about moving hierarchy to composing but didn't grasp the relationship to accessibility. Makes sense here.

**Comment by dajbelshaw** [comment]
Thanks for the input @sometimesmotion & @jgmac1106. Definitely want to make empathy a part of what we're aiming for here with a re-scoped 'Accessibility' competency.

The balance we need to strike is to get at the *spirit* of accessibility on the web, while making the skill descriptors verb-based. This means we (and others) can create activities whereby the learner has either demonstrated an understanding/grasp of that skill, or not.

Does that make sense? Love the suggestions so far - let's keep thinking!

**Comment by jamiea** [comment]
Long since preferred using 'Inclusivity' for this competency. Don't know if this W3 'Designing for Inclusion' overview  is useful for those who haven't seen it. http://www.w3.org/WAI/users/Overview.html

**Comment by dajbelshaw** [comment]
Nice resources @jamiea - thanks for the suggestion! Just wondering how current that is, given that it was last updated three years ago and the W3C now have stuff at the following URL?

http://www.w3.org/standards/webdesign/accessibility

**Comment by dajbelshaw** [comment]
I think we're definitely heading in the right direction here, @jamiea and @sometimesmotion. We're going to be discussing this on this week's community call: https://teach.etherpad.mozilla.org/weblitmap-5feb15

Hope you can both make it!

**Comment by dajbelshaw** [comment]
On this week's community call we hacked away at the skills underpinning the Accessibility competency. Below is what we ended up with, but it's only a starter for ten!

* Using empathy and awareness to inform the design of web content that is accessible to all users
* Designing for different cultures which may have different interpretations of design elements
* Practicing computer use without different senses and skills (sight, hearing, motor control) to physically understand how interfaces may impact users
* Improving the accessibility of a web page through the design of its color scheme, structure/hierarchy and markup

**Comment by jgmac1106** [comment]
- Practicing computer use without different senses and skills (sight, hearing, motor control) to physically understand how interfaces may impact users

This sounds more like an activity to get to an outcome rather than the outcome itself. I would say
- Compare how different interfaces impact diverse users.

**Comment by sometimesmotion** [comment]
I like @jgmac1106's edit and want to add an action verb (I think 'exploring' sounds more exciting than 'practicing,' but either is good)-

* Comparing and exploring how different interfaces impact diverse users

I think that a major change with this simpler wording is the omission of the reference to senses. This omission follows the concept that @jamiea refers to above as 'inclusion' or universal design (designing to everyone regardless of dis/ability, etc.). I think this is more encompassing and inclusive, but may require some explanation. That is to say- for people unfamiliar with the concepts and issues surrounding accessibility & universal design, the skill descriptions may seem vague and too open-ended to be helpful. Perhaps there needs to be a specific reference to universal design in one of the skill descriptions or within the competency descriptor? 

Do we agree that inclusive/universal design is the focus we are aiming for?

**Comment by jamiea** [comment]
+1 that @sometimesmotion but I don't feel that's where we're going with an 'Accessibility' competency.

There's a social argument here in the U.K. I agree with, that 'accessibility' is a semantic dirty-bomb. So I was disappointed to see how the w3 have strengthened it's use over the last couple of years by making it more encompassing in it's definition. That doesn't dilute it as a term for me, however I acknowledge that it's a word with long established practical meaning in terms of web production so it can't be abandoned.
 As my preference was for an 'Inclusivity' type competency that had a broader scope than accessibility, still highlighting it but also including designing for specific devices etc., Now I'm consoling myself that I'm always free to fork it myself!

Great work otherwise folks on the skills

**Comment by dajbelshaw** [comment]
Great work all! So far we've got: 

* Using empathy and awareness to inform the design of web content that is accessible to all users
* Designing for different cultures which may have different interpretations of design elements
* Comparing and exploring how different interfaces impact diverse users
* Improving the accessibility of a web page through the design of its color scheme, structure/hierarchy and markup

Thanks for the input @jgmac1106 and @jamiea. And to answer @sometimesmotion's question while I thank him, I think we're *inspired* (but not tied to) the ideas of universal design.

Keep the ideas coming on this, and other, threads! :)

**Comment by dajbelshaw** [comment]
Closing this in favour of issue #19
