### ISSUE TITLE
  Define skills under 'Search' competency for v1.5

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webliteracymap#23]
**Search** 
*Locating information, people and resources via the web*

* Developing questions to aid a search
* Using and revising keywords to make web searches more efficient
* Evaluating search results to determine if the information is relevant
* Finding real-time or time-sensitive information using a range of search techniques
* Discovering information and resources by asking people within social networks

-----
See spreadsheet at http://goo.gl/R1tjj3

**Comment by dajbelshaw** [comment]
We've got a few suggestions in the REVIEW tab:

* Using and revising keywords to make your web searches more efficient. *(Greg)*
* Evaluating relevancy of search results to locate desired information. *(Greg)*
* Synthesizing across modes and information on a single web page. *(Ian)* 
* Synthesizing info and modes across two or more web pages. *(Ian)*

**Comment by jgmac1106** [comment]
Synthesis always felt stuck in here. Taking information from previous sources and making something new isn't searching.

**Comment by dajbelshaw** [comment]
Interesting, @jgmac1106 - presumably you'd file such synthesis under **Credibility**? Other than the first couple of skills, what else should we cover here? 

We haven't got anything about realtime searching - e.g. on social networks. This is arguably even more important in 2015!

**Comment by jgmac1106** [comment]
Just left similar thought as call ended. When you read competency we explicitly mention finding people but our skills only look at resources:

**Locating people as resources within your communities** Or **Finding people with expertise you need**..

**Comment by sometimesmotion** [comment]
Tweaking the __synthesizing__ piece to be focused on thinking about 1) what information is needed and 2) how the information will be used (rather than actually using it):

* Identifying what information is needed and how it will be used in order to construct and improve upon search strategies

[caveat: this phrasing is awkward]

**Comment by jgmac1106** [comment]
@sometimesmotion I like this idea. you are on to something. maybe...
- Understanding what questions to asked and knowing when they are answered.

**Comment by sometimesmotion** [comment]
@jgmac1106 - I see where you're going and like the simpler approach, but the "improving upon search strategies" piece is important. I'm trying to get at three things that people have difficulty with in searching: 

1. What information do you need to achieve your goal? (e.g. what specific pieces of evidence do you need?)
2. How will you use the information (e.g. who is your audience? do you need jargon-free or jargon-rich content?)
3. These two concepts are important to consider *while* conducting a search. Most people just look for search terms appearing en masse or any form of relevancy to their topic rather than considering whether or not the results will help them with their goal or will be appropriate for their purposes. 1 & 2 are important to consider _during_ the search process, not just in the writing process. If your search results are not helping you meet your goals, how can you adjust your search strategy to find more useful results?

But I'm still not coming up with anything better... Maybe the third point can be a separate skill? 

* Analyzing search results and identifying how to adjust the search strategy when necessary.

**Comment by jgmac1106** [comment]
- Changing search strategies based on audience and task?
- Using search strategies based on audience and task?

I think we cover evaluating search results and revising keywords in the first two schools.

- We do not get at the question, audience, and task that you are discussing.
- Maybe keyword revising and search results evaluating does not capture all the searching strategies?



I see what you mean we do have

**Comment by dajbelshaw** [comment]
Great discussion. Just FYI I've updated the skills at the top of this issue with those we decided upon in this week's community call! http://goo.gl/R1tjj3

**Comment by sometimesmotion** [comment]
Yes- these skills are overlapping and are redundant to a degree. I definitely lost perspective with that. However, I think we need to make each overtly distinct- right now there is a lot of blurry overlap. With the first two, there is no clear (to me) distinction between 'revising searches to be more efficient' and 'evaluating results to locate desired information.' - e.g. when should you revise your keywords without evaluating the relevancy of search results? Perhaps they should be narrowed to cover specific phases of the search process:

* Identifying what information is needed and how it will be used in order to construct a search strategy.
* Identifying and using keywords to efficiently locate desired information. 
          [Tweak of E5 in revise tab: focusing on preparing for a search - dropping the revising piece]
* Evaluating search results to revise the search strategy. 
          [Tweak of F5 in revise tab: focusing on evaluation of results & secondary strategies]

These are now listed in order of how a search strategy should (IMO) be constructed. I made comments on the spreadsheet if this explanation is confusing: [http://goo.gl/R1tjj3](http://goo.gl/R1tjj3)

Also- With the four listed on the review tab, we have two that cover synthesizing the information, which has been argued is not search related, but rather a part of the other competencies- __are we agreeing to leave those out of *Search*?__. My thought is that thinking about _how_ it will be synthesized should be included, but actual synthesis should be elsewhere.

**Comment by dajbelshaw** [comment]
I was fairly convinced after last week's community call that *synthesis* is probably something better to be considered under the **Credibility** competency. 

However, as @sometimesmotion mentions, these competencies blur and overlap to a degree - and that's probably a good thing. What I would say is that the following skill seems to cover a lot of what we're having problems with here: 

* Using and revising keywords to make your web searches more efficient

It's the *revision* after an initial search to make it more focused that's important. Definitely up for adding a fourth skill, but just don't want to make it awkward! I like @sometimesmotion's suggestions, but they do feel quite Information Literacy in focus. ;)

**Comment by jgmac1106** [comment]
Yes lets leave synthesis out for now and just nail down search. 

I think the first two skills caprure the revision of search results @sometimesmotion wants. 

You can evaluate search results without revising keywords, "It is fourth link" 

What is missing is Timsirst skill about thinking about  task.

**Comment by sometimesmotion** [comment]
@dajbelshaw - I've tried, but I can't seem to shake the information literacy mindset! ;)

How about keep the 'using and revising' skill as is but tweak the 'evaluating' to: 
* Evaluating search results to determine if the information is relevant to your needs

This version of 'evaluating' mainly replaces the 'desired information' with relevancy. And that's a big part of what I'm trying to get at- people often just think about what they _want_ rather than what they _need_. I also feel like this gets at 'information need' without getting too specific and librariany. 

Do we want to add a skill about the Deep Web (searching for content beyond the reach of Google)? Perhaps just understanding that Google only searches a small portion of the web?

**Comment by gaditb** [comment]
So this probably isn't really part of Search -- it's part of getting information, though, so? And it's really important, and fits in other places less:

* **Asking Questions** -- asking specific questions, in acceptable places, with as much of the necessary context required for an answer.

It's not Building -- you're not producing anything new. It's not Sharing or Collaborating, for the same reason. It's arguably not Community Participation -- question-spaces don't necessarily have communities. e.g. Yahoo Answers? And more than that, asking for directions doesn't make me a part of a community offline -- online it still shouldn't.

**Comment by jgmac1106** [comment]
I pulled these from the comments from across our stuff.

I agree with @gaditb that we need to get at questioning. 

- Finding real-time or time-sensitive information using a range of search techniques.
- Using and revising keywords to make your web searches more efficient.
- Evaluating search results to determine if the information is relevant to your needs.
- Developing questions related to your goal and knowing when these questions are answered.
- Locating people as resources within your communities (Could help with wording on last one trying to get at social search....we have people in the definition of the competency so need to speak to it....Finding people who have the expertise you need????)

If all of us could semi-finalize a "proposed list" before the Thursday call it might help us. We would need to decide two things:
- Do we boot synthesis?
- What do we need to change about the three proposed skills? (first two approved last week)

**Comment by jgmac1106** [comment]
FYI the two things to decide are on the call when we have list of search skills to present.

**Comment by gaditb** [comment]
@jgmac1106 : Asking questions emphatically *shouldn't* be "within your communities".
People should feel comfortable going into an IRC channel and asking a question.
People should feel comfortable saying "something is wrong, either on your end or mine" into a bug tracker.
People should feel comfortable recognizing what, if any, the help desk for a given product/tool/community is, and how to ring the bell to ask if anyone is in there to answer a question.



That's kinda why, actually, I'm iffy about this category being called "Search" in general -- I know that right now is the wrong time to make an issue out of it, but this category is clearly about Finding Information, and Searching is not the only tool we have or need in our toolbox here. "Search" shouldn't be just Search.

**Comment by gaditb** [comment]
Oh, and I should actually, like respond to the questions:
* My opinion on Synthesis is that Search and Synthesis are actually both skills of the Finding Information competency. Since that's not up for discussion right now, "Synthesis" is definitely the wrong word, if we do keep it. "Evaluating multiple sources to find the limitations of each" is what we want, but probably phrased better (without "evaluating" as a buzzword-ish-thing?). I think we do want that.
* First of all, if we're ordering them, they should be right out reversed. Possibly we actually want "finding real-time information..." to be "Using different search engines or search engine features to search different corpuses" (again, phrased without using a word like "corpus", preferably) -- as in, using Wikipedia if you want Encyclopedic content, using Google News if you want news, using Twitter search if you want current chatter... (basically DuckDuckGo's Bang notation, kinda?)

**Comment by jgmac1106** [comment]
Good point on not being in communities. We define the competency as, **Locating information, people and resources via the web**

We cover *information* and *resources* but don't get to people. Maybe people are covered in real-time and we don't have to be specific??

- I disagree on search and synthesis, and it is still up for discussion. Only the competencies are locked. I am okay if the group wants to keep it under **SEARCH.** 

I just think searching and synthesizing involve different tools, cognitive processes, and social practices.  I see search as setting a question, developing strategies to  answer that question, relevancy judgements of sources and information within sources as you look for answers to that question.

 Once you begin to reshape the information in the source with what you already know and discover you are doing something fundamentally different. Of course you are already doing this as you read but I am referring to explicit steps of combining information from multiple sources.

Not to get too wonky (and I have to double check) but in performance based search tasks scores on synthesis items more often load with scores on evaluation and or composing (could be because Search is a bottle neck skill). Yes measurement comes with its own set of subjectivity and bias, and inquiry isn't linear, but its an interesting data point to consider.

I think this is the perfect time to move search beyond just search and we are probably closer than we think. We would just have to move effectively. 

- I really would love to try and get at our questioning element. I know I have to teach "thick and thin" questions all the time.
- I also think we need to move beyond "search engines" as you suggest and consider people.

**Comment by gaditb** [comment]
**Search:**
Taking Search (the category) as

>setting a question, developing strategies to answer that question, relevancy judgements of sources and information within sources as you look for answers to that question.

Seems like a good way of taking it. I've been interpreting "synthesis" as the third bit, "relevancy judgements of sources and information within sources", so it looks like we're actually agreeing.

If we do take that as our searching, though, we'd want to explicitly state that somewhere -- I feel like to most people, "Searching" for something means "using a search engine".

**People:**
What would "Locating a person" mean besides "Locating information about a specific person"? I'm probably just missing it, but could you give me an explanation or example?

Also: What are "thick and thin" questions?

**Comment by jgmac1106** [comment]
In terns of people over the weekend Doug had a question about photography. He was looking for a specific website. Doug asked on Twitter. Since Doug had curated a list of ecperts to follow he got a few answers right away. His search hinged on the  right people. Not a sesrch engine. 

- Would this event be covered under the first skill? 

As for thick and thin questions I apologize for elementary school lingo. Basically general and specific questions. Can you break a large inquiry task into sets of smaller questions?

**Comment by dajbelshaw** [comment]
This conversation is fascinating, but we're getting stuck in the weeds a little here. Some suggestions:

* Anything about 'synthesis' is probably out of scope until we revisit the competencies with v2.0
* Let's not use 'your' when constructing skills *(this assumes we're addressing learners directly, which we're not)*
* The example that @jgmac1106 mentioned about me trying to locate a photography website at the weekend can be seen [here](https://twitter.com/dajbelshaw/status/574142405823299584) - I agree that it's a nice example of what we're trying to get at!
* We're interested in **web literacy** here, which are *the skills and competencies required to read, write and participate on the web*. While there'll always be edge cases, I'd suggest developing people's questioning skills are out of scope.

How about (as a starter to refine):

* Discovering information and resources by asking people within social networks

Does that work?

**Comment by jgmac1106** [comment]
I like it. This would leave the final search skills for today's call as:

- Finding real-time or time-sensitive information using a range of search techniques. (approved)
- Using and revising keywords to make your web searches more efficient.(approved)
- Evaluating search results to determine if the information is relevant to your needs. (edited needs approval)
- Developing questions related to your goal and knowing when these questions are answered. (proposed)
- Discovering information and resources by asking people within social networks (proposed)

**Comment by jgmac1106** [comment]
The final approved list:

- Developing questions related to your goal and knowing when these questions are answered. 
- Using and revising keywords to make your web searches more efficient.
- Evaluating search results to determine if the information is relevant to your needs. 
- Finding real-time or time-sensitive information using a range of search techniques. (approved)
- Discovering information and resources by asking people within social networks (proposed)

**Comment by dajbelshaw** [comment]
Reopening this as, although great work has been done here, I'm not keen on the use of 'your' in the first three skills and and 'knowing' in the first skill. Perhaps we can rephrase?

* Developing questions to aid a search.
* Using and revising keywords to make web searches more efficient.
* Evaluating search results to determine if the information is relevant. 

I think the last two on @jgmac1106's list are fine. :)

**Comment by jgmac1106** [comment]
We meant to efit out second person. I think it may have been cut and paste error from the pad. 

I think you can go with your rewrite and reclose the issue.

**Comment by jgmac1106** [comment]
And I am really bad at typing on my phone.

**Comment by dajbelshaw** [comment]
OK, updated comment and closing issue!
