### ISSUE TITLE
Define skills under 'Remixing' competency for v1.5

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webliteracymap#27]
**Remixing** 
*Modifying existing web resources to create something new*

* Identifying remixable content
* Combining multimedia resources to create something new on the web
* Shifting context and meaning by creating derivative content
* Citing and referencing original content

-----
See spreadsheet at http://goo.gl/R1tjj3

**Comment by jgmac1106** [comment]
I spent some time thinking about synthesis stuff that we booted from search. There was some talk that this should go under composing. I am thinking it goes under remixing.

When you think about synthesis what are you doing:
*combining web resources with what you know to make a new idea*
*coming up with a summary/gist?TLDR of web resources*

This seems like remixing. This viewpoint also aligns with the New London Group idea of reading/writing as (re)Design.

This then feels like a step before **composing for the web** you can summarize two sources into a new idea and not compose it for the web.

What do folks think? Does synthesis of sources feel like you are remixing those sourrces into a new idea?

**Comment by dajbelshaw** [comment]
Like the idea, @jgmac1106, just think that it would be difficult to construct an activity that demonstrated that. In other words, what would a production-related task look like that involved summarizing two sources into a new idea?

**Comment by jgmac1106** [comment]
A graphic organizer. "Source one says,  source two says,  i say x based on y from source z" 

Or we include a tool like padlet, evernote, etc

**Comment by jgmac1106** [comment]
Or we move synthesis to somewhere elae but remix feels natural you are remixing meaning into something new.

**Comment by dajbelshaw** [comment]
OK, I'm convinced @jgmac1106 :)

How would we define the skill? How would we make it different to *Combining multimedia resources*?

**Comment by jgmac1106** [comment]
While all modes contain meaning we differentiate between information and multimedia. These are the two skills Ian suggested.
- synthesizing  information from a single web page.
- synthesizing information across two or more web pages.

**Comment by jgmac1106** [comment]
There was comment about the need to speak specifically to video and video editing. There was debate if:
- this skills was covered in our more general sense.
- if a skill is needed should it fit under remix, composing, or both.

**Comment by gaditb** [comment]
I disagree with having synthesis here.

The way I've been thinking about these skill in general is:
- **Exploring**: Consuming Content from the Web -- you are interacting with what other people created
- **Building**: Creating Content for the Web -- other people are interacting with what you created
- **Connecting**: Communicating with people on the Web -- you and other people are interacting with each other

Synthesizing is a thing you do yourself -- you're making sense of the information you found from multiple different locations. It's definitely not creating something for other people -- synthesizing information says nothing about publishing it.
I don't know where under Exploring it should go, but it definitely belongs somewhere under Exploring.

**Comment by jgmac1106** [comment]
We can always punt the issue to V 2.0 if we do not come o agreement.

I like your distinction. I would just argue that one you start to reshape what you are reading into something new you are doing a skill fundamentally different than consumption. When I take info from two sources and combine it with my prior knowledge and life experiences I am building something new.

There is also a mindset issue here on where you think meaning lies. There is no right or wrong. Many would argue that meaning making requires activity and since we can't see "what happens in the head" synthesis and comprehension without making is impossible to measure. 

Others may take an information socio-cognitive approach and place meaning making within the individual.

If you can figure out the answer to this philosophical conundrum I will be forever in your debt.

 . .
{--}

**Comment by gaditb** [comment]
Yeah -- I agree with you -- I'm definitely not saying that synthesizing information is "Consumption" in general. However, I would argue that it is a very, very useful distinction is in roughly which direction information is going for a given interaction with/on the web.
And from that perspective, "Synthesizing" is still *getting information from* the web.

Like, I used the word "Consumption", but I didn't even close to mean in with all it's "not creating anything" connotations -- the way I'm thinking about the distinctions between categories, even something like *writing an essay for school* using web sources is "Consuming Content from the Web", because information is going down to you.
(And then, if you formatted and posted that essay on the web, *that* would be "Creating Content for the Web")

**Comment by jgmac1106** [comment]
Final List (Not finished NEED HELP)
- Combining multimedia resources
- Shifting context and meaning by creating derivative content.

**Comment by jgmac1106** [comment]
How about:

- Using video and audio editing tools.

**Comment by gaditb** [comment]
I feel like "citing sources" should be here, though. While technically, its effect is in Open Practices or Community Participation or something -- the action needs to be here. Citing sources cannot be in a separate Competency from Remixing, because you cannot be considered Competent at Remixing if you do not cite your sources. If you are writing and essay for school and you do not cite your sources your essay is just plain wrong. If you publish a work offline and you do not cite your sources, that sometimes gets up to *plagiarism*. Citing sources cannot be in a separate competency, because it has to be considered and actively managed throughout the entire project. The act of citing sources is part of the act of creating a Remix.

**Comment by dajbelshaw** [comment]
I'll just leave these here:

> A remix is a piece of media which has been altered from its original state by adding, removing, and/or changing pieces of the item. A song, piece of artwork, book, video, or photograph can all be remixes. The only characteristic of a remix is that it appropriates and changes other materials to create something new. *(Wikipedia: [Remix](https://en.wikipedia.org/wiki/Remix))*

and:

> Remix culture is a society that allows and encourages derivative works by combining or editing existing materials to produce a new product. A remix culture would be, by default, permissive of efforts to improve upon, change, integrate, or otherwise remix the work of copyright holders. In his book *Remix*, Harvard law professor Lawrence Lessig presents this as a desirable idea. Progress and wealth creation of a culture is fundamentally tied to remixing. *(Wikipedia: [Remix culture](https://en.wikipedia.org/wiki/Remix_culture))*

**Comment by dajbelshaw** [comment]
Listening back to the call, I'm thinking that there's probably a flow here:

* Identifying remixable content
* Combining multimedia resources to create something new
* Shifting context and meaning by creating derivative content
* Citing and referencing original content

**Comment by jgmac1106** [comment]
I like these four! I vote to accept and close the ticket or a tleast keep as is until Monday hack session

**Comment by dajbelshaw** [comment]
:+1:

**Comment by dajbelshaw** [comment]
Done! Thanks for all those who came to the 17th March half-hour hack call. :)
