### ISSUE TITLE
Define skills under 'Sharing' competency for v1.5

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webliteracymap#31]
**Sharing** 
*Providing access to web resources*

* TBD
* TBD
* TBD
* TBD
* TBD

-----
See spreadsheet at http://goo.gl/R1tjj3

**Comment by dajbelshaw** [comment]
Version 1.1 of the Web Literacy Map featured three skills under **Sharing**, all of which have been commented upon and problematised in the [spreadsheet](http://goo.gl/R1tjj3). 

Given we've got somewhat of a blank slate for v1.5 this looks like a good place to start for the [community call on the 5th of March](https://teach.etherpad.mozilla.org/weblitmap-5mar15).

**Comment by dajbelshaw** [comment]
Looking through the comments on the [spreadsheet](http://goo.gl/R1tjj3) it seems like we're trying to get at the following:

* *Why* you should share online
* *How* to share online (e.g. open formats, etc.)
*  Sharing in regards to OER (Open Educational Resources)

Looking at the skills from v1.1 makes them look woefully inadequate. We can do much better! What else do we need to cover?

**Comment by jgmac1106** [comment]
There is so much overlap with collaboration, community practice, and open practice I think the competency will be problematic until a V 2.0 launch.

You obviously have to share to collaborate and if you share in open formats you are engaged in open practices. 

Sharing is such low level fruit (you can send me a file) that fits under so many places.

I think the competency has to go or be seriously revised in V 2.0. I really don't think much can be done in V 1.5 but will wait to hear everyone's thoughts today.

If it were to revise I would want to get at the knowledge work being done under connecting...pull synthesis out of search (where it doesn't belong) and add some other skills. Not sure what I would call competency.

**Comment by RozHussin** [comment]
RE: "sharing = low level fruit"

IMHO, low level fruit is a positive thing. Recognizing and acknowledging the existence of varying levels IS a fundamental skill IN ITSELF.


RE: "...obviously have to share to collaborate..."

True, but you don't necessarily have to collaborate to share. For example, Sal Khan created Khan Academy, and that act of "sharing-online" triggered a whole avalanche of "sharing-as-a-new-teaching-learning-culture". Sal Khan's competency in "sharing" proved to be globally beneficial, but he did not necessarily "collaborate" with everyone who benefited from his "sharing". So, in that light, I would argue that "sharing" SHOULD be defined as a separate competency from "collaborate" (EVEN THOUGH the two are inevitably related, and in some cases, might even be mutually requisite to each other).

**Comment by RozHussin** [comment]
RE: "Why you should share online"

Caveat: The following reasons are NOT conclusive, OR exclusive, OR exhaustive. These are merely my (two cents worth) of randomly sequenced opinions.

(1) When one shares, it demonstrates that person's ability/confidence to self-assess their own competency (in the topic being shared), and the ability to present/demonstrate that competency to another person (who might find that topic beneficial).

(2) When one shares, it is often an act of self-reflection, and a need to seek affirmation/confirmation. Although some people might deem this as a negative (showing off) trait, however, when viewed from a teaching-learning lens, this act of sharing, for purposes of self-benchmarking is a demonstration of proactive self-directed learning.

(3) When one shares with the intent of soliciting responses, this could be seen as a skill to trigger collaboration. However, although one could argue that sharing is a subset of collaboration, the ability to share in-it-self requires specific skills, which may or may not be present in collaboration. For example, while "collaboration" implicitly requires the need for tolerance towards other people's ideas, "sharing", on the other hand, need not.

**Comment by sometimesmotion** [comment]
I agree with Roz above and will re-iterate what has been discussed at past meetings (Marc originally brought this up on [2/19](https://teach.etherpad.mozilla.org/weblitmap-19feb15) to discuss how Building, Sharing and Collaboration are distinct from each other): perhaps we need to tease different meanings from _sharing_, _collaborating_, and _community participation_. 

Considering how these three are different: 
* _Sharing_ can be thought of as _contributing_ your own ideas so that others may use them (passively or actively). 
* _Collaborating_ would be specifically referring to situations in which there is a back and forth between 2+ people. 
* _Community participation_ is then a bigger step up where you are collaborating within a group that has formed a distinct community with a culture. 

[These can be thought of as a hierarchy of involvement- _sharing_ = giving input, _collaborating_  = giving input and receiving feedback, and _community participation_ = becoming accustomed to a culture and sharing & collaborating in ways that are appropriate.]

**My rationale:** In that context, when I think about _sharing_, there are a few skills that come to mind. These skills can easily overlap with Building, so I'm keeping in mind that we are focusing on contributing in a social (active and passive) context- such as thinking about your audience when creating content. In other words, Sharing is focused on social skills whereas Building is focused more on technical skills.

A very rough launching-off point being: 

* Identifying and employing strategies which allow you to feel safe in online social situations
* Determining environments and specific situations in which it is appropriate to contribute
* Considering the environment and audience in order to identify how to make relevant and respectful contributions

**Comment by jgmac1106** [comment]
I like where @rozhussin is going

- Curating web resources for the benefit of others.
- Sharing web resources I create to elicit peer feedback. (too close to design?)
- Reaching new audiences who share a purpose.

**Comment by sometimesmotion** [comment]
@jgmac1106 - I'd want to change "Curating web resources for the benefit of others." to be more inclusive of other types of sharing. Curating is very specific- it is one way to share, but considering how sharing will benefit others is something to consider regardless of what type of content or how you are sharing:

* Sharing content or making contributions for the benefit of others.

This is very close to my third bullet above: "Considering the environment and audience in order to identify how to make relevant and respectful contributions" which includes some more explicit ways that we can 'benefit others.' 

I'm not sure if more general is better- I was about to strikeout my bullet point in favor of this one, but am now ambivalent... General/broad is nice, but specificity can be more helpful for pedagogy/course design.

**Comment by dajbelshaw** [comment]
This is great @RozHussin @jgmac1106 @sometimesmotion :)

My $0.02:

1. You can *curate* without sharing, so I think we should avoid using that particular term until v2.0
2. Using the verb *sharing* within the **Sharing** competency seems to beg the question somewhat - so perhaps we need to get the thesaurus out!
3. I think Greg might be onto something with audiences - and perhaps even e-safety stuff?

Hope that helps. These are probably going to be the hardest skills to define for v1.5!

**Comment by jgmac1106** [comment]
**Contributing  content for the benefit of others**
**Circulating web resources I  create to elicit peer feedback**
**Understanding the needs of audience in order to make relevant contributions**

**Comment by xellpher** [comment]
If we take a look at this from the point of view of the club mentor and one target audience (kids) especially in mind, I think that "low level fruit" needs to be built into the map. Let's say I take up sharing with kids, and the first thing I would bring up is "sending a file" without even mentioning that it is a part of something bigger or "higher level". Once we get to there, it is easy to bring back the skill(s) that have already been learned and say "Ok, let's look at this forum/other community. Remember how we learned to send that file, now you can do the same using this service's tools. Sending files is a part of what collaborating here is all about."

**Comment by jgmac1106** [comment]
@xellpher we do have  **Exporting, moving, and backing up your data from web services** under web mechanics but this doesn't have the community you want to get at. How about

**Creating and using a system to distribute web resources to others**?

**Comment by xellpher** [comment]
Also (after reloading the page and seeing all the comments made to day): does sharing always have to be about what **I have made** (contributing content, web resources I create, relevant contributions)? Is it not sometimes just simply letting someone know about that (cute cat) video I found, which I think someone will enjoy/learn from?

**Comment by xellpher** [comment]
©jgmac1106 I like "Creating and using a system to distribute web resources to others"

**Comment by dajbelshaw** [comment]
+1 to @xellpher's comment that sharing isn't always about sharing *something you've made*.

**Comment by jgmac1106** [comment]
**Contributing content I make and find for the benefit of others
Circulating web resources I create or curate to elicit peer feedback
Understanding the needs of audience in order to make relevant contributions
Creating and using a system to distribute web resources to others**

**Comment by dajbelshaw** [comment]
Nice! The last of these, @jgmac1106, reminds me of using something like [IFTTT](https://ifttt.com/).

**Comment by RozHussin** [comment]
This video interview by Paul Kim, Stanford CTO, talks about "sharing" (as a web literacy), its current impact on education, and the arising issues that are yet to be identified/acknowledged/addressed.
http://youtu.be/RbKCl1a_MZs?t=2m59s

**Comment by sometimesmotion** [comment]
I'm pretty happy with @jgmac1106's master list of the four skills above- I think they reflect what we've discussed except for the e-safety piece. I'd still like to see something about choosing/establishing safe/comfortable ways to share (along the lines of what is discussed in the video @RozHussin shared).

__Identifying when it is safe to contribute content in a variety of situations on web__

**Comment by jgmac1106** [comment]
Make sense. Since we have a security competency would this skill better fit
there or is there a unique safety skill in sharing you and @rozHussin are
discussing?

If so I like what you wrote.

**Comment by sometimesmotion** [comment]
Security is involved, but I'm thinking more about issues like people being aware of ways to feel safe when interacting (specifically sharing) online- I like how it was worded in the video: How do you draw the boundary between things you should share and things you shouldn't share? IMO, sharing is almost a spectrum that is correlated to security:
          no sharing                 =>    too much sharing     
          completely secure     =>    completely insecure 
So that the sharing itself is what is insecure. The risk is sharing too much. You can't share without exposing yourself to some level of risk. The skill, therefore, is gauging that balance. 

So, yes, it is security, but it's also vital part of sharing. My vote is to mention this in Sharing because I see them as intertwined, but I could see it being moved to Security. In some ways, I'm feeling like my thinking on this is circular (chicken<->egg === sharing<->security).

**Comment by dajbelshaw** [comment]
This is great, and I like that we're addressing e-safety in the map without letting it overwhelm everything else. Let's nail these down in an upcoming synchronous session. :)

**Comment by jgmac1106** [comment]
The final and approved skills:
- Creating and using a system to distribute web resources to others. 
- Contributing  and finding content for the benefit of others.
- Creating, curating, and circulating web resources to elicit peer feedback.
- Understanding the needs of audiences in order to make relevant contributions to a community.
- Identifying when it is safe to contribute content in a variety of situations on the web.

**Comment by dajbelshaw** [comment]
<3 it. Have updated first comment.
