### ISSUE TITLE
Define skills under 'Open Practices' competency for v1.5

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webliteracymap#35]
**Open Practices** 
*Helping to keep the web democratic and universally accessible*

* Distinguishing between open and closed licensing
* Making web resources available under an open license
* Contributing to an Open Source project
* Advocating for an open web

-----
See spreadsheet at http://goo.gl/R1tjj3

**Comment by jgmac1106** [comment]
There was a proposed skill of:

- Advocating for an open web (before policy makers).

**Comment by jgmac1106** [comment]
A comment was made that this skill fits in sharing and not open practices:

- Using and sharing files in open, web-friendly formats when appropriate

**Comment by jgmac1106** [comment]
A suggestion was made:

- Attributing openly licensed work used when creating web resources.

**Comment by jgmac1106** [comment]
- Distinguishing between open and closed licensing
- Making web resources available under an open license
- Contributing to an Open Source project
- Advocating for an open web (proposed)
- Attributing openly licensed work used when creating web resources. (proposed)

**Comment by xellpher** [comment]
'Advocating' sounds a little loaded to me. Also, aren't 'Making web sources available under an open license' and 'Contributing to an Open Source project' just that, advocating an open web?

Gadit talks about attributing in the comments for [remixing] (https://github.com/mozilla/webliteracymap/issues/27), and I think he's right. As a skill it fits better there than here, because you should attribute all sources, not just open ones. This was also discussed in yesterday's call.

**Comment by jgmac1106** [comment]
They meant advocacy in a very political sense such as fighting for net
neutrality.

**Comment by dajbelshaw** [comment]
I think we can be more opinionated with this version. I'd be happy to include the proposed skills in the final list.

**Comment by dajbelshaw** [comment]
Great work in today's [half-hour hack session](https://teach.etherpad.mozilla.org/weblitmap-17mar15) means this is finished! :)
