### ISSUE TITLE
Decide whether to order skills within each competency by difficulty

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webliteracymap#37]
We've bumped up against this issue a few times. Lots of people seem to assume that the skills *are* ordered by difficulty. In fact, many seem to think that the competencies within each strand go from easiest to most difficult.

Whether or not we explicitly communicate the fact, we have a decision to make as to whether we make an attempt to order the skills within each competency by difficulty. What do **you** think?

**Comment by jamiea** [comment]
It hadn't even occurred to me that lots of folk might read the skills in this way. Now I'd ask why not order the skills ? Seems like it might be an aid, especially for self-developing learning pathways within a competency.

**Comment by dajbelshaw** [comment]
Thanks @jamiea! Definitely interested in what others think, but will just point out that when we were doing the initial work we wanted each to be a node on a network rather than a static ladder within a particular competency.

For example:
![WebLit Learning Pathways](https://d23f6h5jpj26xu.cloudfront.net/ofmkiskccwoxaw_retina.png)

http://literaci.es/weblit-learning-pathways

**Comment by jgmac1106** [comment]
For me it isn't so much about a progression . That being said I think we
should be deliberate in listing the "easiest" first. This has more to do
with buy in and "marketing" more than instructional design.

It is the same reason you often put the easiest problem on a test first. So
in coding/scripting *reading and explaining the structure of code* makes
more sense first then *composing working loops and arrays. *It just doesn't
scare away users.

Is is also more logical. That is my other question when deciding what
should go first: Does this make sense for example in Designing for the
Web *Using
CSS properties to chnage the style and layout of a webpage *just makes more
sense coming before *demonstrating the diferrence between inline, embedded
and external CSS. *

So I don't think we we have to scope at all the skills in the map just be
deliberate in what we list first and make sure if a progression exists in
some places it is done because logic and not a subjective value of judgment
of skills dictates the order.

**Comment by jamiea** [comment]
Acknowledged @dajbelshaw, personally I've never seen it otherwise. Just seems if "lots" of people are seeing the skills as being ordered anyway, with no prompting other than perhaps by reading habit, there might be things to be gained by taking advantage of this.
Think it was @jgmac1106 who previously suggested rearranging the skills in Web Mechanics to help with the flow of the skills section there.

**Comment by jamiea** [comment]
Also IMO the current visual design does more than anything else to encourage a tiered view of the content (& thought this was one of the bigger changes mooted for v2.0?)

**Comment by dajbelshaw** [comment]
Interesting stuff - thanks for the thinking @jamiea and @jgmac1106! What I'm hearing is that there's a kind of 'cognitive ease' that we should take advantage of here?

**Comment by jamiea** [comment]
Nicely put.

**Comment by dajbelshaw** [comment]
We decided on the 5th March community call to do this where it makes logical sense.
